from datetime import datetime
from typing import List

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from src.core.schemas import HookAnalysisReport, OfferMatrixSummary, TacticalCreativeBrief

ACCENT = colors.HexColor("#e63946")
BG_DARK = colors.HexColor("#1e2130")
TEXT_LIGHT = colors.HexColor("#ffffff")
TEXT_MUTED = colors.HexColor("#9ca3af")
ROW_ALT = colors.HexColor("#24283b")


def _make_styles():
    base = getSampleStyleSheet()

    cover_title = ParagraphStyle(
        "CoverTitle",
        fontSize=32,
        textColor=TEXT_LIGHT,
        alignment=TA_CENTER,
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )
    cover_sub = ParagraphStyle(
        "CoverSub",
        fontSize=14,
        textColor=TEXT_MUTED,
        alignment=TA_CENTER,
        spaceAfter=4,
        fontName="Helvetica",
    )
    section_header = ParagraphStyle(
        "SectionHeader",
        fontSize=16,
        textColor=ACCENT,
        spaceAfter=8,
        spaceBefore=16,
        fontName="Helvetica-Bold",
    )
    field_label = ParagraphStyle(
        "FieldLabel",
        fontSize=9,
        textColor=TEXT_MUTED,
        spaceAfter=2,
        fontName="Helvetica-Bold",
    )
    field_value = ParagraphStyle(
        "FieldValue",
        fontSize=11,
        textColor=TEXT_LIGHT,
        spaceAfter=10,
        fontName="Helvetica",
        leading=15,
    )
    hook_item = ParagraphStyle(
        "HookItem",
        fontSize=11,
        textColor=TEXT_LIGHT,
        spaceAfter=6,
        fontName="Helvetica",
        leftIndent=12,
        leading=15,
    )
    return {
        "cover_title": cover_title,
        "cover_sub": cover_sub,
        "section_header": section_header,
        "field_label": field_label,
        "field_value": field_value,
        "hook_item": hook_item,
    }


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(TEXT_MUTED)
    canvas.setFont("Helvetica", 8)
    canvas.drawCentredString(A4[0] / 2, 18 * mm, "Generated by AdLens PK")
    canvas.drawRightString(A4[0] - 20 * mm, 18 * mm, f"Page {doc.page}")
    canvas.restoreState()


def export_report_pdf(
    offer_matrix: OfferMatrixSummary,
    hook_report: HookAnalysisReport,
    brief: TacticalCreativeBrief,
    output_path: str,
) -> None:
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=24 * mm,
        bottomMargin=28 * mm,
    )
    styles = _make_styles()
    story = []

    # ── Cover Page ──────────────────────────────────────────────────────────
    story.append(Spacer(1, 60 * mm))
    story.append(Paragraph("AdLens PK", styles["cover_title"]))
    story.append(Paragraph("Pakistani Digital Ad Intelligence Engine", styles["cover_sub"]))
    story.append(Spacer(1, 4 * mm))
    story.append(HRFlowable(width="100%", thickness=2, color=ACCENT))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(f"Niche: {brief.target_niche}", styles["cover_sub"]))
    story.append(Paragraph(f"Report Date: {datetime.now().strftime('%Y-%m-%d')}", styles["cover_sub"]))
    story.append(PageBreak())

    # ── Section 1: Market Overview ───────────────────────────────────────────
    story.append(Paragraph("Section 1 — Market Overview", styles["section_header"]))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT, spaceAfter=8))

    metrics = [
        ("Total Ads Evaluated", str(offer_matrix.total_ads_evaluated)),
        ("COD Adoption Rate", f"{offer_matrix.cod_prevalence_pct:.1f}%"),
        ("Free Shipping Prevalence", f"{offer_matrix.free_shipping_prevalence_pct:.1f}%"),
        ("Most Common CTA", offer_matrix.most_common_cta),
        ("Dominant Hook Type", hook_report.dominant_hook_type),
        ("Dominant Language", hook_report.dominant_language),
        ("Price Ranges Detected", ", ".join(offer_matrix.price_ranges_detected) or "None"),
    ]

    metric_table_data = [["Metric", "Value"]]
    for k, v in metrics:
        metric_table_data.append([k, v])

    metric_table = Table(metric_table_data, colWidths=[90 * mm, 80 * mm])
    metric_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_LIGHT),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 11),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 10),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_LIGHT),
        ("BACKGROUND", (0, 1), (-1, -1), BG_DARK),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [BG_DARK, ROW_ALT]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#2d3148")),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))
    story.append(metric_table)
    story.append(PageBreak())

    # ── Section 2: Top 10 Ads Table ──────────────────────────────────────────
    story.append(Paragraph("Section 2 — Top 10 Ads Overview", styles["section_header"]))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT, spaceAfter=8))

    ads_data = [["Page Name", "Price", "COD", "CTA"]]
    col_w = [70 * mm, 30 * mm, 20 * mm, 40 * mm]
    for rec in offer_matrix.records[:10]:
        ads_data.append([
            rec.page_name,
            rec.price_mentioned or "N/A",
            "Yes" if rec.has_cash_on_delivery else "No",
            rec.primary_cta,
        ])

    ads_table = Table(ads_data, colWidths=col_w)
    ads_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_LIGHT),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_LIGHT),
        ("BACKGROUND", (0, 1), (-1, -1), BG_DARK),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [BG_DARK, ROW_ALT]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#2d3148")),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("WORDWRAP", (0, 0), (-1, -1), True),
    ]))
    story.append(ads_table)
    story.append(PageBreak())

    # ── Section 3: Hook Psychology ────────────────────────────────────────────
    story.append(Paragraph("Section 3 — Hook Psychology Analysis", styles["section_header"]))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT, spaceAfter=8))

    hooks_data = [["Page Name", "Hook Type", "Language", "Raw Hook"]]
    hook_col_w = [45 * mm, 40 * mm, 25 * mm, 55 * mm]
    for item in hook_report.items[:20]:
        truncated = item.raw_hook[:60] + ("..." if len(item.raw_hook) > 60 else "")
        hooks_data.append([item.page_name, item.hook_type, item.language, truncated])

    hooks_table = Table(hooks_data, colWidths=hook_col_w)
    hooks_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_LIGHT),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_LIGHT),
        ("BACKGROUND", (0, 1), (-1, -1), BG_DARK),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [BG_DARK, ROW_ALT]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#2d3148")),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("WORDWRAP", (0, 0), (-1, -1), True),
    ]))
    story.append(hooks_table)
    story.append(PageBreak())

    # ── Section 4: AI Strategy Brief ─────────────────────────────────────────
    story.append(Paragraph("Section 4 — AI Tactical Strategy Brief", styles["section_header"]))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT, spaceAfter=8))

    story.append(Paragraph("TARGET NICHE", styles["field_label"]))
    story.append(Paragraph(brief.target_niche, styles["field_value"]))

    story.append(Paragraph("MARKET WHITESPACE", styles["field_label"]))
    story.append(Paragraph(brief.market_whitespace, styles["field_value"]))

    story.append(Paragraph("RECOMMENDED PSYCHOLOGICAL ANGLE", styles["field_label"]))
    story.append(Paragraph(brief.recommended_angle, styles["field_value"]))

    story.append(Paragraph("RECOMMENDED OFFER STRUCTURE", styles["field_label"]))
    story.append(Paragraph(brief.recommended_offer_structure, styles["field_value"]))

    story.append(Paragraph("SUGGESTED COPY HOOKS", styles["field_label"]))
    story.append(Spacer(1, 3 * mm))
    for idx, hook_text in enumerate(brief.suggested_hooks, start=1):
        story.append(Paragraph(f"{idx}.  {hook_text}", styles["hook_item"]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
